FROM php:8.3-apache

RUN docker-php-ext-install pdo pdo_mysql && \
    apt-get update && apt-get install -y curl

RUN a2enmod rewrite

RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf